@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "id": "S20210001",
    "password": "S20210001"
}
###

@token = {{login.response.body.token}}

# @name 成功（200）
GET  {{baseUrl}}/api/student/subjects
X-Auth-Token: {{token}}
###

# @name 成功（200）
GET  {{baseUrl}}/api/student/subjects/1
X-Auth-Token: {{token}}
###

# @name subjectIdが存在しない場合（404）
GET  {{baseUrl}}/api/student/subjects/4
X-Auth-Token: {{token}}
###