spring:
    application:
        name: api
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    data:
        redis:
            host: localhost
            password: 
            port: 6379