spring:
    application:
        name: sotsuken-api
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    data:
        redis:
            host: ${REDIS_HOST}
            password: 
            port: ${REDIS_PORT}