@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "id": "T00000001",
    "password": "T00000001"
}
###

@token = {{login.response.body.token}}

# @name 成功
GET  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}


###

# @name subjectIdが存在しない場合に404エラーが返る
GET  {{baseUrl}}/api/teacher/subjects/4
X-Auth-Token: {{token}}


###

# @name 成功
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "startDate": "2024-01-01",
  "finishDate": "2024-02-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S20210001"
  ]
}

###

# @name subjectIdが存在しない場合に、404エラーが返る
POST  {{baseUrl}}/api/teacher/subjects/4
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "startDate": "2024-01-01",
  "finishDate": "2024-02-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S20210001"
  ]
}

###

# @name subjectNameが空文字列の場合に400を返す
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName":"",
  "startDate": "2024-01-01",
  "finishDate": "2024-02-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S20210001"
  ]
}

###

# @name startDateがfinishDateよりも前の日付のときに400を返す
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "startDate": "2024-02-01",
  "finishDate": "2024-01-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S20210001"
  ]
}

###

# @name teacherIdが存在しないIdを渡したとき400
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "startDate": "2024-01-01",
  "finishDate": "2024-02-01",
  "teacherId": "",
  "studentIds": [
    "S20210001"
  ]
}

###

# @name 存在しないstudentIdsを渡したときuserIdは保存されない
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "startDate": "2024-01-01",
  "finishDate": "2024-02-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S202100011"
  ]
}

###

# @name startDateもしくはfinishDateが存在しない場合400エラー
POST  {{baseUrl}}/api/teacher/subjects/1
X-Auth-Token: {{token}}
Content-Type: application/json

{
  "subjectName": "subject 1",
  "finishDate": "2024-02-01",
  "teacherId": "T00000001",
  "studentIds": [
    "S20210001"
  ]
}

###