@baseUrl = http://localhost:8080

# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "id": "T00000001",
    "password": "T00000001"
}
###

@token = {{login.response.body.token}}

# @name 成功
GET  {{baseUrl}}/api/teacher/subjects/1/lectures
X-Auth-Token: {{token}}
###

# @name subjectIdが存在しない場合(404)
GET  {{baseUrl}}/api/teacher/subjects/4/lectures
X-Auth-Token: {{token}}
###


# @name subjectIdが存在しない場合（404）
POST  {{baseUrl}}/api/teacher/subjects/0/lectures
X-Auth-Token: {{token}}
Content-Type: application/json

[
  {
    "lectureName": "string",
    "date": "2024-11-26",
    "periods": 0
  }
]
###

# @name subjectIdが正常に入力されている場合（200）
POST  {{baseUrl}}/api/teacher/subjects/1/lectures
X-Auth-Token: {{token}}
Content-Type: application/json

[
  {
    "lectureName": "string",
    "date": "2024-11-26",
    "periods": 0
  }
]
###