services:
  spring:
    image: api:0.0.2-SNAPSHOT
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:latest
    restart: unless-stopped

volumes:
  postgres-data:
